language: node_js
sudo: false
branches:
  only:
    - master
node_js:
  - '8'
  - node
cache:
  - npm: true
  - directories:
    - node_modules
before_script:
  - npm run build
script:
  - npm run build
  # - npm run lint
